version: '3.7'
services:
  app:
    working_dir: /srv
    restart: "always"
    env_file:
      - prod.env
    build:
      context: ./application
      dockerfile: docker/app/Dockerprod
      args:
        ENVIRONMENT: "production"
        DEBUG: 0
    ports:
      - 127.0.0.1:8080:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/apprepo/medias:/srv/medias:cached
